name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
      run: echo Hello, world!
      
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
        # mail server settings
         server_address: smtp.gmail.com
         server_port: 587
    # user credentials
         username: sunitha.kotta@ovaledge.com
         password: {{secrets.password}}
    # email subject
         subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
         body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    # comma-separated string, send email to
         to: kottasunitha1997@gmail.com, sunithakotta9795@gmail.com
    # from email name
         from: Sunitha

        

